server {
    listen 5000;
    server_name 86e35cbf-c93f-48cd-be34-fefd431b2147.cloud.ce.kmitl.ac.th;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}