export const breadcrumbNameMap = {
  main: 'หน้าหลัก',
  departments: 'ข้อมูลภาควิชา',
  programs: 'ข้อมูลหลักสูตร',
  users: 'ข้อมูลผู้ใช้งาน',
  'edit-user': 'แก้ไขข้อมูลผู้ใช้งาน',
  subjects: 'ข้อมูลรายวิชา',
  rubrics: 'ข้อมูล Rubric กลาง',
  'edit-rubric': 'แก้ไขข้อมูล Rubric',
  'course-in-program': 'รายวิชาในหลักสูตร',
  'student-data': 'ข้อมูลนักศึกษากลาง',
  plos: 'การกำหนดผลการเรียนรู้ระกับหลักสูตร PLO',
  teacher: 'ข้อมูลหลัก',
  'mapping-plo': 'การเชื่อมโยงผลการเรียนรู้กับรายวิชา',
  teacherDashboard: 'รายวิชาที่รับผิดชอบ',
  subjectStudents: 'รายชื่อนักศึกษาของรายวิชา',
  studentGroups: 'กลุ่มงานนักศึกษา',
  courseOutcomes: 'ผลการเรียนรู้รายวิชา',
  gradingWeights: 'สัดส่วนคะแนน',
  learningActivities: 'กิจกรรมการเรียนรู้ในรายวิชา',
  teachingPlan: 'แผนการสอน',
  activityScores: 'คะแนนกิจกรรมการเรียนรู้',
  courseResults: 'ผลลัพธ์การเรียนรู้รายวิชา',
  studentResults: 'ผลลัพธ์การเรียนรู้รายบุคคล',
  learningDetails: 'รายละเอียดผลการเรียนรู้',
  outcomeActivityMapping: 'ความเชื่อมโยงผลการเรียนรู้และกิจกรรม',
  'course-in-term': 'การเปิดรายวิชาในภาคการศึกษา',
  behaviors: 'พฤติกรรมที่วัดผลได้ตาม CLO',
  attention: 'ระดับการบรรลุผลพฤติกรรม',
  AddNewActivity: 'เพิ่มกิจกรรมใหม่',
  AssessmentCLO: 'การประเมินผลการเรียนรู้',
  AssessmentCriteria: 'หลักฐานการประเมิน',
  ContinuousImprove: 'การปรับปรุงอย่างต่อเนื่อง',
  programLevelByIntake: 'ผลการเรียนรู้ระดับหลักสูตรตามปีรับเข้า',
  programLevelIndividual: 'ผลการเรียนรู้ระดับหลักสูตรรายบุคคล',
  programLevelCompare: 'เปรียบเทียบผลการเรียนรู้ระดับหลักสูตร',
  programLevelAllStudents: 'ผลลัพธ์การเรียนรู้ระดับหลักสูตร',
  'user-history': 'ประวัติการใช้งาน',
}
